title: Wizard of Norrland
description: Your site description here
baseurl: ""
url: https://wizardofnorrland.net

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown

# Exclude files from processing
exclude:
  - .github/
  - .gitignore
  - README.md
